### ISSUE TITLE
Maximum length is 999mm

### ISSUE THREAD

**Issue by jajberni** [URJCMakerGroup/MakerWorkbench#27]
By definition, in the Qt controls, the maximum length for the aluminum profile is 999mm. It would be great to allow longer distances for bigger designs: 

https://github.com/URJCMakerGroup/MakerWorkbench/blob/e4df9f4637d291f0ffb81b8c7714cb34fb700619/Gui/Aluprof_Gui.py#L69

These profiles can be purchased up to 3m in theory. 

Congratulations on this great development!!!

**Comment by davidmubernal** [comment]
Hi!
Thanks for your feedback. I have change the maximun length to 9999

I hope this solve the issue. If you have any other upgrade in mind let me know!
