### ISSUE TITLE
readme is not visible from Addon Manager in FreeCAD 0.21

### ISSUE THREAD

**Issue by bitbasher** [URJCMakerGroup/MakerWorkbench#32]
this WB addon shows up on the list but when clicked it fails to open the Readme file with this message

> Could not load README data from URL 
> https://github.com/URJCMakerGroup/MakerWorkbench/blob/main/README.md
> 

i am running in Windows 11

**Comment by davidmubernal** [comment]
Thanks @j3ffrw to fix this ❤️
