### ISSUE TITLE
Workbench uniformity

### ISSUE THREAD

**Issue by luzpaz** [URJCMakerGroup/MakerWorkbench#5]
- [x] Please move all icons in to `MakerWorkbench/Resources/icons/`
- [ ] If you are translating the workbench please create a `Resources/translations` directory (have you successfully been able to translate the workbench? I've seen indications in the source code)
- [x] Rename icons so that the workbench name precedes the name of the icon. This is future-friendly since FreeCAD documentation is striving to make all documentation uniform for better interoperability within itself and external workbenches. The convention is `<Workbenchname>_<Command>.svg`
- [x] Fix #4 
- [x] Remove pycache files `https://github.com/URJCMakerGroup/MakerWorkbench/tree/master/Gui/__pycache__`
- [x] Change README.md `Web` section name to `Documentation` so it's less generic

**Comment by davidmubernal** [comment]
Hi Luzpaz,

Thanks for the list of _things to do_. I do un update with some of these things.

Unfortunately, I can't prove that problem #4 is complete. I hope to do a PullRequest to FreeCAD with the requirements in the following days.

Regarding the translation, this is something we would like to have in the long term. If you have any tutorial about how to do this, that would be a great help.

Thank you for supporting the project

**Comment by luzpaz** [comment]
Good enough for now. Translation if there is demand can come later
